'use client';

import Link from 'next/link';
import type { Trip } from '@/lib/trips';

export function TripCanvas({ trip, shared = false }: { trip: Trip; shared?: boolean }) {
  const total = trip.experience.budget_breakdown.reduce((sum, line) => sum + line.amount, 0);
  return <main className="aurora-page min-h-screen px-4 py-5 text-zinc-100 sm:px-8"><div className="mx-auto max-w-6xl">
    <header className="glass flex items-center justify-between rounded-2xl px-5 py-4"><Link href="/" className="flex items-center gap-2"><b className="grid h-8 w-8 place-items-center rounded-xl bg-violet-300 text-zinc-950">R</b>RoamVerse</Link>{!shared && <Link href={`/share/${trip.share_slug}`} className="rounded-xl border border-white/10 px-3 py-2 text-sm hover:bg-white/10">Share journey ↗</Link>}</header>
    <section className="mt-7 overflow-hidden rounded-[24px] border border-white/10 bg-gradient-to-br from-violet-500/20 via-zinc-900 to-sky-600/15 p-7 sm:p-10"><p className="text-xs font-medium uppercase tracking-[.2em] text-violet-200">{shared ? 'A RoamVerse Journey Drop' : 'Your generated journey'}</p><h1 className="mt-3 max-w-3xl text-4xl font-medium tracking-[-.05em] sm:text-6xl">{trip.experience.title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-zinc-300">{trip.experience.premise}</p><div className="mt-7 flex flex-wrap gap-2 text-sm text-zinc-300"><span className="rounded-full bg-black/20 px-3 py-1.5">{trip.destination}</span><span className="rounded-full bg-black/20 px-3 py-1.5">{trip.start_date} — {trip.end_date}</span><span className="rounded-full bg-black/20 px-3 py-1.5">{trip.travelers} traveler{trip.travelers > 1 ? 's' : ''}</span></div></section>
    <section className="mt-4 grid gap-4 lg:grid-cols-12"><article className="glass rounded-[22px] p-6 lg:col-span-8"><p className="text-sm font-medium">Journey timeline</p><div className="mt-6 space-y-5">{trip.experience.itinerary.map((day) => <div className="grid gap-3 border-l border-violet-300/40 pl-5 sm:grid-cols-[80px_1fr]" key={day.day}><p className="text-xs uppercase tracking-wider text-violet-200">Day {day.day}</p><div><h2 className="text-lg">{day.title}</h2><p className="mt-1 text-sm text-zinc-400">{day.theme}</p><ul className="mt-3 flex flex-wrap gap-2">{day.moments.map((moment) => <li className="rounded-lg bg-white/[.06] px-2.5 py-1.5 text-sm text-zinc-300" key={moment}>{moment}</li>)}</ul></div></div>)}</div></article>
    <aside className="glass rounded-[22px] p-6 lg:col-span-4"><p className="text-sm font-medium">Map signal</p><div className="mt-4 grid min-h-48 place-items-center rounded-2xl bg-[radial-gradient(circle_at_55%_45%,rgba(196,181,253,.35),transparent_8%),radial-gradient(circle_at_35%_70%,rgba(125,211,252,.22),transparent_8%),linear-gradient(135deg,#171324,#101b28)]"><div className="text-center"><span className="text-2xl">✦</span><p className="mt-2 text-sm">{trip.experience.map_center}</p></div></div><div className="mt-4 space-y-2">{trip.experience.map_points.map((point) => <p className="text-sm text-zinc-400" key={point}>· {point}</p>)}</div></aside></section>
    <section className="mt-4 grid gap-4 md:grid-cols-3"><article className="glass rounded-[22px] p-5"><p className="text-sm font-medium">Budget</p><p className="mt-2 text-2xl">{trip.currency} {total.toLocaleString()}</p><p className="mt-1 text-xs text-zinc-500">of {trip.currency} {trip.budget.toLocaleString()} planned</p><div className="mt-5 space-y-3">{trip.experience.budget_breakdown.map((item) => <div className="flex justify-between text-sm" key={item.category}><span className="text-zinc-400">{item.category}</span><span>{item.amount.toLocaleString()}</span></div>)}</div></article>
    <article className="glass rounded-[22px] p-5"><p className="text-sm font-medium">Weather window</p><p className="mt-4 text-sm leading-6 text-zinc-300">{trip.experience.weather.summary}</p><p className="mt-4 text-xs font-medium uppercase tracking-wider text-violet-200">Pack smart</p><p className="mt-2 text-sm text-zinc-400">{trip.experience.weather.packing_note}</p><p className="mt-3 text-sm text-zinc-400">{trip.experience.weather.contingency}</p></article>
    <article className="glass rounded-[22px] p-5"><p className="text-sm font-medium">Food radar</p><div className="mt-4 space-y-4">{trip.experience.food.map((food) => <div key={food.name}><div className="flex justify-between text-sm"><span>{food.name}</span><span className="text-violet-200">{food.price}</span></div><p className="mt-1 text-xs text-zinc-500">{food.neighborhood} · {food.why}</p></div>)}</div></article></section>
    <section className="mt-4 grid gap-4 md:grid-cols-2"><article className="glass rounded-[22px] p-5"><p className="text-sm font-medium">Hidden gems</p><ul className="mt-4 space-y-3 text-sm text-zinc-300">{trip.experience.hidden_gems.map((item) => <li key={item}>✦ {item}</li>)}</ul></article><article className="glass rounded-[22px] p-5"><p className="text-sm font-medium">Packing edit</p><div className="mt-4 flex flex-wrap gap-2">{trip.experience.packing.map((item) => <span className="rounded-full bg-white/[.07] px-3 py-1.5 text-sm text-zinc-300" key={item}>{item}</span>)}</div></article></section>
  </div></main>;
}
