import Link from 'next/link';

const content: Record<string, { eyebrow: string; title: string; copy: string; cards: string[] }> = {
  dashboard: { eyebrow: 'Your travel workspace', title: 'Quietly brilliant journeys, all in one place.', copy: 'Start a new Journey Drop, return to a saved story, or explore the signals your agents are holding onto.', cards: ['Create a cinematic escape', 'Continue a shared journey', 'Your taste profile is evolving'] },
  timeline: { eyebrow: 'Journey timeline', title: 'Every day has a feeling.', copy: 'Your experience will unfold as a story arc, with room for spontaneity.', cards: ['Day 01 — Arrival ritual', 'Day 03 — Local texture', 'Day 07 — The lasting moment'] },
  agents: { eyebrow: 'Agent thinking', title: 'A transparent team behind every decision.', copy: 'See what each specialist is considering before the Coordinator creates your final Journey Drop.', cards: ['Planner — sequencing the experience', 'Food — finding local character', 'Weather — protecting the feeling'] },
  budget: { eyebrow: 'Budget intelligence', title: 'Spend on moments, not friction.', copy: 'A living financial view that helps your group make choices with confidence.', cards: ['Stay — balanced comfort', 'Food — intentional discovery', 'Experiences — leave room for wonder'] },
  food: { eyebrow: 'Food discovery', title: 'Taste the place, not the algorithm.', copy: 'Your Food Agent collects textures, neighborhoods, and flavors worth remembering.', cards: ['Morning ritual', 'The local table', 'One unforgettable night'] },
  weather: { eyebrow: 'Weather intelligence', title: 'Prepared, never over-planned.', copy: 'Seasonal context and graceful contingencies woven into the journey.', cards: ['Seasonal signal', 'Packing edit', 'Beautiful backup plan'] },
  profile: { eyebrow: 'Your travel profile', title: 'Your taste, becoming clearer.', copy: 'RoamVerse learns only from the travel details you choose to keep.', cards: ['Slow mornings', 'Food-forward cities', 'Unexpected landscapes'] },
};

export function WorkspacePage({ page }: { page: string }) {
  const data = content[page] ?? content.dashboard;
  return <main className="aurora-page relative overflow-hidden px-5 py-5"><div className="aurora-blob one"/><div className="aurora-blob three"/><div className="relative mx-auto max-w-6xl"><header className="glass flex h-16 items-center justify-between rounded-2xl px-5"><Link href="/" className="flex items-center gap-2"><b className="grid h-8 w-8 place-items-center rounded-xl bg-violet-200 text-zinc-950">R</b>RoamVerse</Link><nav className="hidden gap-5 text-sm text-zinc-400 md:flex"><Link href="/dashboard">Dashboard</Link><Link href="/create">Create</Link><Link href="/agents">Agents</Link></nav></header><section className="py-16"><p className="text-xs font-medium uppercase tracking-[.22em] text-violet-200">{data.eyebrow}</p><h1 className="mt-4 max-w-3xl text-4xl tracking-[-.055em] sm:text-6xl">{data.title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-zinc-400">{data.copy}</p><div className="mt-10 grid gap-4 md:grid-cols-3">{data.cards.map((card, index)=><article className="glass card-hover rounded-[22px] p-5" key={card}><span className="text-xs text-violet-200">0{index+1}</span><h2 className="mt-10 text-lg">{card}</h2><div className="skeleton shimmer mt-4 h-2 w-4/5"/><div className="skeleton shimmer mt-2 h-2 w-3/5"/></article>)}</div><Link href="/create" className="mt-8 inline-block rounded-2xl bg-white px-5 py-3 text-sm font-medium text-zinc-950">Create a Journey Drop →</Link></section></div></main>;
}
